### ISSUE TITLE
VLC Now Playing display the application name (in other languages then English)

### ISSUE THREAD

**Issue by namaless** [JimmyAppelt/Snaz#113]
Preview: https://puu.sh/rWnek/d66d4a7e1d.png

You can see the window name with the application name, the best way in general I think is a really good start point to add the possible in the Now Playing section to remove a string you can choose, in my case I wanna remove `- Lettore multimediale VLC'` found in the text file.

Thanks for this great software.

**Comment by JimmyAppelt** [comment]
Hi @namaless 

Yes this comes because you have a different langue selected in VLC itself.

You can change the language like so:

![e1cfd6a1831af2f936bf79edfc163136](https://cloud.githubusercontent.com/assets/5420393/19736657/8f82bcf2-9bb0-11e6-9aa8-ce7767a5a95e.png)

*(the window title will be "VLC media player", and will be deleted automatically)*

**Comment by namaless** [comment]
Yeah I know that, but I think when you have time you can add this for every locale versions 👍
