### ISSUE TITLE
Make countdowns able to account for daylight savings time

### ISSUE THREAD

**Issue by GravenImageRD** [JimmyAppelt/Snaz#117]
About to do the Extra Life gaming marathon and want to countdown to my end time of 8am tomorrow morning. In order to account for "fall back" at 2am when the clock rolls back to 1am, I have to set my end time to 9am and will have to remember to change it during the night. Would be rad if you added some special case code to account for adding or subtracting an hour from a countdown due to daylight savings time!

**Comment by jcolsen** [comment]
Countdown to a spesific time uses your computers clock. So, when your clock automatically adjusts for daylight savings, so will the countdown. In other words, don't worry about it, it already does that :D

**Comment by GravenImageRD** [comment]
Right, but 8am today to 8am tomorrow is 25 hours, not 24, so it isn't technically accurate until time jumps back. It's way too early in the morning to remember if the C# DateTime and/or TimeSpan has a handy way to do that for you or not. You'd think I would since writing C# is what I do for a living. :)

**Comment by jcolsen** [comment]
I'm a bit confused as to what you're trying to do. If all you want to do is to count down 24 hours without worrying about that, you can use Chrono Down instead. Keep in mind that daylight savings is not a global event.

**Comment by JimmyAppelt** [comment]
Well technically the countdown works perfect as @jcolsen mentions, but it indeed doesn't previews DST changes. I understand that calculating these is more correct.

Also @jcolsen has a good point with:
> daylight savings is not a global event
So this is indeed a choice you have going to make when choosing a countdown or chrono down.

I uploaded a Beta client .. where it will preview these DST changes, and adapt with adding or subtracting an hour depending on these changes.

You can download it [here](http://jimmyappelt.be/snaz/beta/) *1.12.4.4 beta 0.1*

Since it's a beta, i would appreciate feedback for this specific change.

**Comment by GravenImageRD** [comment]
Awesome, and yeah, would definitely want it as something that could be toggled on or off based on your region since like you said not everyone observes it. I'll check it out! Thanks a bunch!

**Comment by JimmyAppelt** [comment]
@GravenImageRD you won't have to turn it of, it will be checked region dependently.

**Comment by GravenImageRD** [comment]
Even better! Gave it a whirl, set a count down to go until March 12th next year and it popped the UI and accounted for Spring Forward and the time looked correct, also set my system time back a day and checked for Fall Back and worked like a charm. Exactly what I was hoping for. :)

**Comment by JimmyAppelt** [comment]
@GravenImageRD great ! Thanks for reply.
