### ISSUE TITLE
Multiple Text Line Changer Colomns /link .txt/.xml files to any line or column

### ISSUE THREAD

**Issue by FatherlyArson** [JimmyAppelt/Snaz#145]
this image was edited not an acutal coded program
this is a mockup of a feature suggestion.
![snaz](https://cloud.githubusercontent.com/assets/25243669/24841479/8b24afa4-1d4b-11e7-8d38-76bcb5cd5733.PNG)
Multiple rows
the ability to link .txt/.xml files to any line or column 
textline 1 operates the same as snaz 1.12.5.0
textline 2(Recent Donator.txt=[genertaed by streamlabs app])
textline 3(Recent Follower.txt=[generated by streamlabs app])
textline 4 operates the same as snaz 1.12.5.0

**Comment by BeezerP** [comment]
I am looking for something similar - streamlabs and muxy generate .txt files for all the tracking categories (followers, subscribers, cheerers, hosts, etc). I am looking for something that could be scrolling text line (like in OBS scrolling text set up of "read from file") that would rotate through a number of files. EXAMPLE: having one place on screen dedicated to a scrolling line where the contents rotate through recent followers, then  recent cheerers, then recent subscribers, then recent donators, then recent hosts, then top donators, etc.  This would allow all that information you might want to share on stream but not take up so much screen real estate because it would all go to same area of one line.
So if the text line changer could add ability to read a local dynamic txt file - or something...

**Comment by MikeJ-AK** [comment]
I would love a feature like BeezerP is describing.

I prefer a minimalist look to my overlays and having all that info on a scrolling single line would be perfect.

I've actually been trying to make this work all morning with Snaz and OBS.

**Comment by ThatGirlSlays** [comment]
I too would like to see the text line changer read from a file.
