### ISSUE TITLE
Now Playing Info/Controls Fail When Foobar Is Set To Minimize To Tray

### ISSUE THREAD

**Issue by SPIKEYPUP** [JimmyAppelt/Snaz#154]
If Foobar is set to Minimize To Tray Snaz appears to be unable to "see" the player and it's activity; and the controls on the Now Playing tab of Snaz do not produce expected results when buttons are pressed, also the tag or meta data fails to load or be shown.  For example, pressing Play/Pause or Next produces no results whether player is currently in playback mode, or if standing by (not playing/stopped or paused).

Current Workaround: Do Not Set Foobar to Minimize To Tray.

Thanks for such an excellent app!  I couldn't stream without it, and I don't know how I did before I had it...

**Comment by JimmyAppelt** [comment]
Hi @SPIKEYPUP 

It's expected behavior, since Snaz has to have access to the foobar window itself. If you minimize to the tray there is no window.

Snaz does not access or reads tags or meta data from the music files. Please take a look on this wiki page note: https://github.com/JimmyAppelt/Snaz/wiki/Playing-Now 

> Album and album art are query-ed from a database (will respond with the first match, if any) for all players except iTunes, you are able to get the album and album art you set within iTunes

**Comment by SPIKEYPUP** [comment]
Sorry for the delayed response, thank you for clarifying this, makes total sense and understood.  Thanks for doing all your hard work on an excellent applet!  :)
