### ISSUE TITLE
combine static and dynamic sources

### ISSUE THREAD

**Issue by iamvroom** [JimmyAppelt/Snaz#21]
It would be great if you could combine text sources both static and dynamic into one e.g.

in the text line changer tab you could specify "latest follower: " + path('c:\test.txt') for the application to combine the two into one text field going "latest follower: minime"

**Comment by JimmyAppelt** [comment]
Its is a great idea ...

I would even combine it with all that snaz has to offer such as {currenttime}, {chronoup} etc.

Al trough i have to completely rewrite the textile changer for that. As it was not originally intended to do this stuff. Its being a few years ago since i wrote the text line changer so i never had the idea that Dynamic files would be a feature in the future.

But i love the idea and would be a great feature.

**Comment by iamvroom** [comment]
would also work if we could assign custom IDs (tags) to the dynamic files and then use these IDs to reference the content in the text changer.

**Comment by JimmyAppelt** [comment]
Thtas what i meant with `{currenttime}` and `{chronoup}` :wink:

**Comment by JimmyAppelt** [comment]
I believe this is what you are after:

![preview](https://i.gyazo.com/3a8bd7408b031f873ef8d8637b28e050.gif)

**Comment by iamvroom** [comment]
yes, how do I see the available things?

**Comment by JimmyAppelt** [comment]
@iamvroom this was a test of me (its not in the current public client)

**Comment by iamvroom** [comment]
awww :( It looks so awesome XD
