### ISSUE TITLE
Request - create albumart/now playing images

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#26]
have an idea to show album art in a slideshow using OBS.. This works fine now by adding the Snaz folder holding the image but as I run the slideshow over an information panel with text (and have a transparent images in every other position in the show to display the text between images) I need a way to both scale the album art down and compose it over a background to hide the text on the box.. Hope you get what I am saying..😉 Optimal would be to be able to have an x by x image with the albumart on the left and track title/artist on the right ..(edited)

**Comment by JimmyAppelt** [comment]
I'm not really 100% sure what you are trying to do, but you can scale the image of the album art immediately inside obs.

**Comment by paulheu** [comment]
On my overlay I have a panel with current game info. On top of that I run a slideshow with a transparent image to show the game info . What I am looking for is a way to overlay album art scaled to 200x200 over an existing empty box so it covers the text completely. See attached images.

I think this option would be something useful to more people then just me..

![overlay panel](https://cloud.githubusercontent.com/assets/12208547/11613300/e69ca16c-9c13-11e5-9e01-2f09264d8ba6.png)
![bottombox_albumart](https://cloud.githubusercontent.com/assets/12208547/11613301/e6b3470a-9c13-11e5-9505-1c24a6b59f73.png)

**Comment by JimmyAppelt** [comment]
That's perfectly possible to do already :wink: (You can scale the image inside the OBS preview window)

![sample](https://i.gyazo.com/ec18e20f43411e16e04e6670c48e195f.gif)

> Note :
Assuming that you are using `OBS 0.657 ` and not the MP version because i haven't seen any slideshow option in MP, the Image Slide Show will not pickup if the album art has changed. Its 
not coded in OBS. Only the normal Image Source will pick up the changes.

**Comment by paulheu** [comment]
Yes, I know I can scale one image, I cant however not scale one image in a series from a folder I am showing a slideshow from, unless I scale the slideshow as a whole.

The point is, there is text on the background which will show on the left and right of the image. HereJ's a quick recording of what I mean, maybe it helps..

http://1drv.ms/1HOzZgt

**Comment by JimmyAppelt** [comment]
Right, i see what you mean now.

Its a little bit of a cheat you want to pull of :smile: 

But how would it matter if the image of the album art is not updating when you change song ?
You always will have the same album art image all the time anyway.

**Comment by paulheu** [comment]
True, it's somewhat of a cheat.. I did find a possible way to do this in PHP although I have no real idea of how to implement this locally and I have no experience really in writing PHP (but am guessing it's not that hard) It would then also mean I'd have to do a trigger when the album art changes, composite the scaled albumart on the preset background and copy the result into the slideshow folder.. 

All doable  I guess, it would just be nice if Snaz could do this.. If there is no album art it defaults to a 1x1 image which could be checked for. It's just an idea I had.. if it's not really feasible to do that's fine..

**Comment by JimmyAppelt** [comment]
OBS itself doesn't check for image changes in the slideshow :wink: that's why it wont update.

A more feasible and easier approach would be:

* Create Image in OBS with the album art (changes will be detected)
* Create Text with track Info (changes will be detected)
* Run a slideshow on top of these from your own folder (with a transparent image between it, to reveal the album art and 
song info once and a while)

![sample](https://i.gyazo.com/5df6481eff0d40f15fa1335d01d9e9a8.gif)

**Comment by paulheu** [comment]
Would be fine with me to close this..

**Comment by JimmyAppelt** [comment]
Ok @paulheu thank you, you can always close a ticket (if you made it yourself) by yourself.
