### ISSUE TITLE
Spotify randomly stops playing

### ISSUE THREAD

**Issue by jayeeyee** [JimmyAppelt/Snaz#36]
Since the latest update (1.12.1.0), I've had issues where Spotify randomly stops playing or fails to auto play the next song. This occurs randomly and usually after a song is finished. I've noticed this problem occurring after the latest update. I have spotify on shuffle and album repeat.

**Comment by JimmyAppelt** [comment]
Hi @jayeeyee 

I tried to replicate this (with Shuffle and repeat on) ... everything is functioning fine here.

Its seems weird to me that you have this problem from **1.12.1.0** since i didn't touch the spotify code since previous release (only changes were made to foobar2000 and winamp).

Are you using the latest version of spotify `1.0.20.94.g8f8543b3` ?
Do you have multiple programs that are detecting the trackinfo ?

**Comment by jayeeyee** [comment]
I'm using Spotify 0.9.15.27. I have another app running which blocks ads from Spotify. Other than that only Snaz is drawing up the track info.

**Comment by JimmyAppelt** [comment]
Then you might want to try out a few things:

* Disable the Blockify
* Update spotify to the latest client (i recommend you always do) - (i know that blockify probably wont work on the new update)

**Comment by JimmyAppelt** [comment]
If you still have any questions about this, feel free to re-open the issue
