### ISSUE TITLE
AM/PM Clock moving

### ISSUE THREAD

**Issue by GCar** [JimmyAppelt/Snaz#53]
When the clock displays "1" it will shorten and extend the time. 
![d39a1bfbc1e8d0ba7ce1db2a97403c8f](https://cloud.githubusercontent.com/assets/16796924/12447189/28be5e9e-bf34-11e5-989a-64dd30be7559.gif)

**Comment by JimmyAppelt** [comment]
hi @GCar 

This is due to the font you are using. The digit `1` holder is much smaller then all the other digits.
Sadly enough there is nothing i can do to fix this.

* You can choose another font that doesn't have this problem
* You can put Am/Pm in front of the time and align the whole time to the left (if you're stream software lets you
* You can stop using seconds

**Comment by JimmyAppelt** [comment]
Will close this ticket as the answer is pretty solid to you're question.

In case you have any other questions regarding this issue, feel free to re-open the ticket.
