### ISSUE TITLE
Playing Now feature not working

### ISSUE THREAD

**Issue by XSfanatic** [JimmyAppelt/Snaz#6]
The text file that was supposed to be created that has the playing now feature wasn't created and it won't let me create one for it.
![a65bba78c9ded22a1f431453b89401f9](https://cloud.githubusercontent.com/assets/15143791/10517548/dd9dae68-7322-11e5-8376-f5bd08221ba5.png)

**Comment by JimmyAppelt** [comment]
Hey @XSfanatic could you try running snaz as administrator ?

**Comment by JimmyAppelt** [comment]
I've changed the setup file to not recommend Program Files anymore from 1.10.0.2

Snaz requires the need of writing access into sub directory's - ether u need to run Snaz as administrator if it is installed into a Program Files directory or install Snaz into a non Program Files directory.

This is part of Windows behavior :)

**Comment by XSfanatic** [comment]
Hi, Sorry I got distracted with other things. That did work thank you for the help

**Comment by JimmyAppelt** [comment]
Your'e welcome :+1:

**Comment by JimmyAppelt** [comment]
If u uninstall previous versions and install version 1.10.0.5 this problem is not addressed anymore as changed some settings in the installer.

Download link [here](http://jimmyappelt.be/download/snaz)

So this problem will happen to all previous version that where installed under: 
`C://Program Files/JimsApps/Snaz` or `C://Program Files (x86)/JimsApps/Snaz`

The new default file directory for snaz will be:
`C://Program Files/Snaz` or `C://Program Files (x86)/Snaz`
