### ISSUE TITLE
Microsoft .NET Framework issue

### ISSUE THREAD

**Issue by JoelFardal** [JimmyAppelt/Snaz#76]
Microsoft .NET Framework says something is wrong and all of my previously instated settings are gone, it's also not writing on any of the files.
![microsoft net](https://cloud.githubusercontent.com/assets/19495839/15710896/3d782b08-280c-11e6-869f-294340cfcabe.png)

What does this mean? I don't know, but it's broken.

**Comment by JimmyAppelt** [comment]
Hi @JoelFardal 

It is a pretty common .Net Issue. Its was already issue ed by another users #63  

You have the error probably because Snaz was not closed or closed incorrectly.

Your config file is corrupt (this can be caused due not closing snaz before shutting down the computer for example)

1. Close Snaz
2. Delete the folder `JimsApps` in `C:\Users\YOURUSERNAME\AppData\Local\`
3. Restart Snaz

**Comment by JoelFardal** [comment]
Danke schön

**Comment by JimmyAppelt** [comment]
> When this happens Snaz will prompt you to ask if you want to fix this automatically from 1.12.4.3
