### ISSUE TITLE
Now Playing - Error importing data Foobar 2000

### ISSUE THREAD

**Issue by Quejicas** [JimmyAppelt/Snaz#78]
Use Now Playing tab with Foobar 2000 but I'm having problems importing data from Foobar.

I do not correctly recoonoce album name, sometimes recognizes biem and others not. This problem also makes the CD cover is not correct.

Another mistake I encounter is that the buttons "Next" and "Prev" not jump to the correct track.

I leave a video demonstration of error: https://vimeo.com/171276139

Sorry for the possible grammatical errors. I do not speak English and I am using Google Translator

**Comment by JimmyAppelt** [comment]
Hi @Quejicas,

The behavior of the album name and art is absolutely normal, this is because the information is not pulled from foobar2000 or ID3 tag.

The information is pulled from a online database owned by spotify *(the largest database available)* ... the song must exist in the database and needs to be spelled correctly.

For the second part of you're issue .. the songs that are skipped ... we need to investigate that a bit more since i'm unable to replicate it.

**Comment by Quejicas** [comment]
thank you very much for the information, check the names of camciones and liken with Spotify. Best regards
